version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.3.0
    - 3.5.1
    - 3.5.2
    - 3.6.5
    - 3.7.0
    - 3.8.1
    - 3.9.1
    - 4.1.10
    - 4.1.5
    - 4.1.6
    - 4.1.9
  - dependency-name: gatsby
    versions:
    - 2.32.0
    - 2.32.1
    - 2.32.10
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.0
